# version: '3.8'

# services:
#   backend:
#     build:
#       context: ./backend/gasstation/gasstation
#       dockerfile: Dockerfile
#     container_name: backend
#     environment:
#       SPRING_DATASOURCE_URL: jdbc:h2:file:/app/database/db
#       SPRING_DATASOURCE_USERNAME: sa
#       SPRING_DATASOURCE_PASSWORD: password
#     ports:
#       - "8080:8080"
#     volumes:
#       - ./database:/app/database
#     networks:
#       - app-network

#   frontend:
#     build:
#       context: frontend
#       dockerfile: Dockerfile
#     container_name: frontend
#     ports:
#       - "3000:80"
#     volumes:
#       - ./frontend:/usr/share/nginx/html
#     depends_on:
#       - backend
#     networks:
#       - app-network

# volumes:
#   mysql_data:


# networks:
#   app-network:
#     driver: bridge
version: '3.8'

services:
  backend:
    build:
      context: ./backend/gasstation/gasstation
      dockerfile: Dockerfile
    container_name: backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:file:/app/database/db
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"
    volumes:
      - ./database:/app/database
    networks:
      - app-network

  frontend:
    image: nginx:alpine # Use the pre-built nginx:alpine image
    container_name: frontend
    ports:
      - "3000:80"
    volumes:
      # Mount frontend files directly into the container
      - ./frontend/html:/usr/share/nginx/html
      - ./frontend/css:/usr/share/nginx/html/css
      - ./frontend/js:/usr/share/nginx/html/js
      # Mount the custom Nginx configuration
      - ./frontend/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
